build.nix
builtins/default.nix

Apparently the `cargolock` env var can become too big so we replace it with a file. This fixes the following error:
```
building 
'/nix/store/s8bv90acizsyvh1s9gk7yvpiyw2gcpnx-dfinity-application-and-others-deps.drv'... 
while setting up the build environment: executing 
'/nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23/bin/bash': 
Argument list too long
```
See the following on the background of why env vars can become too big:
https://stackoverflow.com/questions/28865473/setting-environment-variable-to-a-large-value-argument-list-too-long

Pass cargolock/cargotoml via file instead of via env var

---

build.nix
default.nix

In the deps derivation the docs are already contained in `target` which is copied to `$out`. So in that case also copying the docs to a separate `$doc` output wastes space. Only the final derivation should have its docs in a separate `$doc` output.

Don't copy the docs to a separate doc output for the dependencies

---

build.nix
default.nix
lib.nix
test.nix

* fix tests on Linux
* improve the per-crate build to not recompile on install and ...
* ... actually drop the per-crate build, thanks @basvandijk 
* run clippy and other on deps (which was then removed)
* fix `--release` flag
Let's see what we broke!

Bunch of improvements

---

default.nix
lib.nix
test.nix
test/simple-dep-patched/Cargo.lock
test/simple-dep-patched/Cargo.toml
test/simple-dep-patched/my-rand/Cargo.toml
test/simple-dep-patched/my-rand/src/lib.rs
test/simple-dep-patched/src/main.rs
test/workspace-patched/Cargo.lock
test/workspace-patched/Cargo.toml
test/workspace-patched/bar/Cargo.toml
test/workspace-patched/bar/src/main.rs
test/workspace-patched/foo/Cargo.toml
test/workspace-patched/foo/src/main.rs
test/workspace-patched/my-rand/Cargo.toml
test/workspace-patched/my-rand/src/lib.rs

This allows users to override the source of crates using:
```
[patch.crates-io]
bar = { path = 'my/local/bar' }
```

Copy paths from the [patch] section into the dummy-src

---

README.md
build.nix
default.nix
lib.nix

* general build code cleanup
* reduce number of derivations built
* remove occurrences of `foo`, `bar` and other silly names
* set name and version based on package metadata

Clean up, take 2

---

build.nix
config.nix
default.nix

The code had gotten so hairy I couldn't follow anymore. This splits out the configuration in its own file, and differentiates the configuration that's used during the build vs. the configuration that's used when planning the build.

Refactor configuration

---

build.nix
builtins/default.nix
config.nix
default.nix
test.nix

* Don't make use of builtins.fetchurl but use nixpkgs'
* Use the `pathExists` builtin when possible, the custom one is a bit greedy
* Fetch the `Cargo.lock` and others from an unfiltered source (`root`)

Fix evaluation for restrict-eval

---

README.md
config.nix
test.nix

The documentation building step takes a fair bit of time and most users
won't care about it. By default we turn it off.

Disable doDoc by default

---

.gitignore
flake.nix

This allows you to use naersk more easily via the current version of [nix-flakes](https://youtu.be/UeBX7Ide5a0) (though it may rapidly change syntax, maybe it should be on its own branch for now) :)  
Btw, I saw your speech on NixCon via YouTube, it's really good!
Before:
```nix
{
inputs.naersk = {
url   = "github:nmattia/naersk";
flake = false;
};
packages = forAllSystems (system: {
rnix-lsp = let
naerskBuilt  = nixpkgs.legacyPackages."${system}".callPackage naersk {};
in naerskBuilt.buildPackage {
name = "rnix-lsp";
src  = cleanSourceSomehow ./.;
root = ./.;
};
});
}
```
After:
```nix
{
inputs.naersk = {
url   = "github:nmattia/naersk";
};
packages = forAllSystems (system: {
rnix-lsp = naersk.lib."${system}".buildPackage {
name = "rnix-lsp";
src  = cleanSourceSomehow ./.;
root = ./.;
}; …
```

Basic flake.nix

---

lib.nix

This adds a dummy `build.rs` in `dummy-src` to ensure build dependencies are built.

Ensure build-dependencies are built

---

build.nix

out.json will never exist because we make a temporary file stored in
`$cargo_build_output_json`.
---
In #62, the `cargo build` errors were redirected to a `$cargo_build_output_json` file, but when attempting to retrieve these errors, tried to `cat` out.json (which never existed).

Fix failure to `cat` out.json when `cargo` errors

---

build.nix
default.nix

When there are too many crate dependencies the `crates.io` derivation will fail with:
```
while setting up the build environment: executing '/nix/store/rm1hz1lybxangc8sdl7xvzs5dcvigvf7-bash-4.4-p23/bin/bash': Argument list too long
builder for '/nix/store/pbbnw6y6zggqddy244ix5nyysamcgm0j-crates-io.drv' failed with exit code 1
```
This is caused by the [`paths` environment variable of `symlinkJoin`](https://github.com/NixOS/nixpkgs/blob/fc592a52cacfbf5f22e6479a22263983f5346ea6/pkgs/build-support/trivial-builders.nix#L250) exceeding the limit.
This is fixed by having our own version of `symlinkJoin` called `symlinkJoinPassViaFile` which passes `paths` via a file instead of via an environment variable.
I think this should be fixed in the upstream `symlinkJoin` so I'll provide a PR for that …

Fix too big environment variable `paths` in `symLinkJoin`

---

build.nix

`libtest` defaults to the number of cores which is often too much parallelism.

Set RUST_TEST_THREADS="$NIX_BUILD_CORES" to reduce parallelism

---

.github/actions/nix/install-nix
config.nix
test/cargo-wildcard/Cargo.toml

I ran across this issue when trying to build [nushell](https://github.com/nushell/nushell/tree/1ec2ec72b5d772db8759905e03cb34b6409f5067). Their [Cargo.toml](https://github.com/nushell/nushell/blob/1ec2ec72b5d772db8759905e03cb34b6409f5067/Cargo.toml#L16) has a trailing slash in the globbing pattern, which breaks naersk with the same error seen in #53 
This fix addresses that specific issue, however the `members` field actually accepts a much more extensive [globbing syntax](https://docs.rs/glob/0.3.0/glob/struct.Pattern.html), at least according to the docs.
I'm hoping that more involved cases are relatively rare in practice. If anyone has a more extensive/less error-prone way of handling this, please do!

Make sure `expandMember` works with a trailing slash

---

build.nix

When cargo is instructed to build code for a different target, it will store the
output under `target/<host-triple>`. This means that some docs will be under
`target/<triple>/doc` and some under `target/doc`.
This change takes into the account the existence of `CARGO_BUILD_TARGET` and
uses that to discover newly created docs when copying/processing.

Handle documentation for different targets

---

README.md
config.nix
default.nix

This adds `overrideMain f` which is equivalent to calling
`drv.overrideAttrs f`.
Closes #105 
CC @cole-h

Make top-level override easier

---

build.nix
default.nix

I don't know if this was the original intended behavior or not, but since `$key` (i.e. the git rev) is originally placed at the end of the directory name, long enough keys mean it eventually gets truncated altogether. In this case it's breaking having dependencies on two different git checkouts of bytecodealliance/wasmtime.

Avoid key collision in git dependencies

---

README.md
README.tpl.md

I noticed that the current templates aren't perfect - they use `pkgs.callPackage naersk {}` which is pointless since naersk has a `flake.nix`. I also added a template that supports a custom rust version, in case someone needs that

Improve nix flake templates

---

config.nix
default.nix
lib.nix

This is an alternative to https://github.com/nmattia/naersk/pull/135 ; that doesn't try to implement path dependency parsing, as:
1. it'd need to be done recursively, which requires more work
2. it'd have to make sure that workspaces with path dependencies don't end up breaking most if not all the benefits of two-derivation caching
3. in most cases manually filling in `copySources` should not be too bad a thing to do (eg. to compile `cargo` I just had to set `copySources = ["crates"]`), and anyway to get more of the benefit of two-derivation caching there would be very hard (impossible?)
What do you think about this PR?

Expose copySource for dealing with path-based dependencies

---

lib.nix

This should fix #109 I believe. I'm not quite sure of the code, especially the `matchByName` function, but it works perfectly on one of my projects and also passes the tests.

feat: use the revision from Cargo.lock

---

lib.nix

This is required so that fetching dependencies from a feature branch is
possible.
See also https://github.com/NixOS/nix/pull/3408

make fetchgit work when not fetching from master

---

build.nix
rust/binary.nix
rust/cargo.nix
rust/clippy.nix
rust/libunwind.nix
rust/rls/default.nix
rust/rustc.nix
rust/rustfmt.nix

- `stdenv.lib` → `lib`
- `pkgconfig` → `pkg-config`
This fixes a runtime warning.

Remove deprecated aliases

---

lib.nix

Flake sources are nix derivations, which means they automatically get made read-only. This causes overwriting Cargo.toml and potentially build.rs fail. The cure to this is to either chmod the sources after copy, or in this case copy without preserving the file's original mode.

Support flake-based workspaces

---

builtins/to-toml.nix

Fixes https://github.com/nmattia/naersk/issues/148.
"As of rust-lang/cargo@7dd9872, Cargo adds a new `version = 3` key to
the lockfile's top level"

fix(builtins/to-toml): support int type

---

lib.nix

Fixes #142
The target  `thumbv7m-none-eabi` has only `libcore` without `libstd`.
We should make `dummy-src` to be `no_std` when cross-compiling to these target (by setting `build.target` in `.cargo/config`).

Avoid accidentally pulling `std` for no-std crates

---

lib.nix

This reverts commit 79129b5c16d299b747b5276afd80b1f325f786ac.
This fixes https://github.com/nmattia/naersk/issues/149

Revert "make fetchgit work when not fetching from master"

---

build.nix

I'm not really sure exactly what changed in more recent versions of rustc but now we need this.

Add libiconv as a dependency for everything on macOS

---

.github/workflows/test.yml

Some tests like the wasm one were never executed because they are
neither --fast, nor tested in the main CI.
This copies the fast.yml into test.yml, minus the --fast flag.

ci: run all tests on master

---

config.nix

Don't rely on unstable flags.

---

flake.nix

This adds support for the new Apple Silicon processors (aarch64-darwin) which are used in Macbook M1. 
We successfully use this in our project https://github.com/yaxitech/ragenix.

Add support for aarch64-darwin

---

build.nix
test.nix

* Previously the CARGO_TARGET_DIR environment was set to the `out`
directory which resulted in cargo placing all of its artifacts there
instead of the default `target` directory
* Later on, the build scripts would then copy the (empty) `target`
directory to `$out` resulting in cargo rebuilding the entire
dependency tree from scratch whenever the top level crate's source was
changed
* Now we omit the CARGO_TARGET_DIR environment variable and inspect the
`target` directory for any binaries instead of the `out` directory
Fixes #202

Fix copying cargo artifacts from deps

---

README.md
README.tpl.md
examples/cross-windows/flake.nix
examples/hello-world/flake.nix
examples/multi-target/flake.nix
examples/static-musl/flake.nix

Replace nmattia with nix-community.
The templates should contain a nix-community not nmattia reference.

README and templates cleanup

---

.gitignore
config.nix

This will `throw` a more explanatory error message when Cargo.lock is missing form root.

Better error missing cargo lock

---

.github/workflows/fast.yml
.github/workflows/test.yml
nix/sources.json
nix/sources.nix

* Update to a more recent revision of nixpkgs
* Add nixpkgs-21.11 for testing
* Add nixpkgs-21.05 for testing
* Drop nixpkgs-20.09, branch is EOL
* Drop nixpkgs-20.05, branch is EOL
* Bump ripgrep-all to v0.9.6 to make tests pass

ci: bump nixpkgs versions

---

lib.nix

Without this change you'd get errors like this when adding a
`git`-dependency to a `Cargo.toml` which is pinned to a tag:
fetching Git repository 'git://github.com/ma27/nixpkgs-fmt'fatal: couldn't find remote ref refs/heads/v1.2.0-rnix-0.10
error: program 'git' failed with exit code 128

Correctly fetch git tags

---

.github/CODEOWNERS

Since I'm kinda new to the nix-community organization, I'm not _entirely_ sure on this process, but as a maintainer, adding myself to codeowners seems natural 🙂

chore: Add myself to .github/CODEOWNERS

---

lib.nix

The usage of git "rev" dependencies in Cargo implies that the rev
will be found regardless of ref.  This is currently not true in naersk;
the following dependency fails:
usbfs = {git = "https://github.com/goertzenator/usbfs-rs", rev = "7c35b46e41ad76f838cd99b493f9337f475b5b70"}

force fetchGit allRefs when a dependency is specified with "rev"

---

lib.nix

Starting from a clean Nix fetcher cache, Naersk incorrectly handles dependencies from a `Cargo.lock` when they come from a `git+ssh://` URL at a specific tag, assuming no branch of the same name exists.
This usually shows up as an error like
```
fetching Git repository 'ssh://git@some.private.git.server/repo.git' fatal: couldn't find remote ref refs/heads/some_tag
```
indicating that `builtins.fetchGit` is attempting to fetch `refs/heads/some_tag` instead of `refs/tags/some_tag` as expected.
This is easy to fix: if we need to use `builtins.fetchGit` to download sources, use a more explicit, unambiguous `ref` argument depending on whether a `branch` or `tag` was specified for that entry in `Cargo.lock`.
Nix's impure fetcher cache can conceal this problem, at least with my version of Nix …

Disambiguate branch/tag refs passed to fetchGit

---

README.md
config.nix
lib.nix
nix/sources.json
test/slow/default.nix
test/slow/nushell/default.nix

Our current Cargo.toml discovery algorithm is based on reading the main Cargo.toml and looking at its `workspace.members` - unfortunately, as it turns out there's actually no requirement for all workspace crates to be listed there, and some applications do fancy things like:
```toml
[workspace]
members = [ "crates/foo" ]
[dependencies]
foo = { path = "crates/foo" }
bar = { path = "crates/bar" } # whoopsie
```
... which doesn't play nice with Naersk's incremental builds (that is, the compilation fails unless `singleStep = true;` is turned on).
This commit changes the logic to use a different approach: now we simply recursively scan the root directory, noting down all the Cargo.tomls we find; Crane seems to use the same algorithm.
I think the only case where this approach falls short are …

Improve Cargo.toml discovery algorithm

---

README.md
README.tpl.md
nix/sources.json
nix/sources.nix
test/slow/agent-rs/default.nix
test/slow/nushell/default.nix

When CMake builds a project, it generates a file called `CMakeCache.txt` that contains - among others - a dump of environmental variables.
This file is generated both for the deps-only- and the main- derivation, and if env-vars happen to differ between both¹, CMake will refuse to compile the latter derivation, saying:
```
CMake Error: The current CMakeCache.txt directory ... is different than the directory ... where CMakeCache.txt was created.
```
Solving this problem is easy - one just has to remove `CMakeCache.txt` to let CMake regenerate it.
Note that the original bug report (linked below) suggests to use `sed`, but that doesn't work on Darwin which uses a different convention for temporary paths - compare error messages for the failing derivations:
... on Linux:
```
CMake Error: The …
```

Support incremental builds with CMake

---

README.md
README.tpl.md

Closes https://github.com/nix-community/naersk/issues/277.

readme: Add a section on `overrideAttrs`

---

flake.nix

Otherwise, `nix flake check` fails:
```
grahamc@Grahams-Air naersk % nix flake show --no-write-lock-file
warning: not writing modified lock file of flake 'git+file:///Users/grahamc/projects/naersk':
• Added input 'nixpkgs':
'github:NixOS/nixpkgs/12bdeb01ff9e2d3917e6a44037ed7df6e6c3df9d' (2023-10-15)
git+file:///Users/grahamc/projects/naersk?ref=refs/heads/master&rev=3f976d822b7b37fc6fb8e6f157c2dd05e7e94e89
error: attribute 'defaultTemplate.description' does not exist
```

Add descriptions so nix flake check passes

---

README.md
README.tpl.md

We're not looking for a maintainer anymore! 😄

readme: removed maintainer status

---

build.nix
nix/sources.json
test/slow/probe-rs/default.nix

This PR fixes the nightly warning
```
warning: `/build/probe-rs-src/.cargo-home/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
```
Also bumps the probe-rs sources and the rust nightly version used for testing it

Fix .cargo-home/config warning on nightly, bump probe-rs

---

build.nix
default.nix

Nixpkgs now has much more reasonable handling of macOS SDKs, and this old default is not generally needed  for builds anymore.
I think having these SDKs in the inputs is a bit of a nuisance now, since it means there are mixed framework versions in the closure.
See: https://discourse.nixos.org/t/on-the-future-of-darwin-sdks-or-how-you-can-stop-worrying-and-put-the-sdk-in-build-inputs/50574
See: https://github.com/NixOS/nixpkgs/pull/346043
Note: this is also tagged at https://github.com/DeterminateSystems/naersk/releases/tag/apple-sdks for use.

Drop macOS SDKs that follow "the old way"

---

flake.nix

Those are deprecated in Nix:
https://github.com/NixOS/nix/pull/12068

don't use indirect nixpkgs references

---

build.nix

Relay non-JSON lines in cargo output
Forward both JSON log messages from `cargo test` and non-JSON messagse from the test binary itself.
(Note: the test binaries do have a `--format` option, but the "json" format is unstable and so can only be used by nightly `cargo`)
Fixes: https://github.com/nix-community/naersk/issues/353

Fix jq parse error when cargo test runs a failing test
