- README.md
> Add comparison to rustPlatform and carnix

- default.nix
There's now a single function `buildPackage` that one can call with `singleStep = true` to skip the pre build ("some-name").
> Simplify configuration for single step build

- README.md
- build.nix
- config.nix
- default.nix
- test.nix
> Allow attribute set _or_ path in buildPackage

- build.nix
- builtins/default.nix
- builtins/to-toml.nix
- config.nix
- default.nix
- lib.nix
- test.nix
What do you think of the format @nmattia ?
> format with nixpkgs-fmt

- lib.nix
> Add support for new lockfile format

- README.md
- README.tpl.md
> Add example for nixpkgs-mozilla to README

- default.nix
- lib.nix
I believe this should resolve the issue of shortrevs being passed to fetchgit (#48)
> Resolve #48

- .github/workflows/fast.yml
- nix/default.nix
- nix/sources.json
- script/test
- test.nix
> Run tests on 19.09 and 20.03

- rust/1_38_0.nix
- rust/1_41_0.nix
- rust/binary.nix
- rust/bootstrap.nix
- rust/cargo.nix
- rust/clippy.nix
- rust/default.nix
- rust/libunwind.nix
- rust/print-hashes.sh
- rust/rls/default.nix
- rust/rust-src.nix
- rust/rustc.nix
- rust/rustfmt.nix
- rust/setup-hook.sh
- test.nix
> Copy rustc 1.41.0 from nixpkgs and adapt for custom targets

- test.nix
Closes #95 
CC @nomeata I haven't tried this yet, just letting the CI do its thing!
> Add test wasm32 build

- build.nix
- default.nix
Remove some noise from the build config
> Light cleanup

- flake.nix
- overlay.nix
A convenience utility. This makes it easier to integrate naerks with
other flakes that initialize nixpkgs.
> add overlay

- flake.nix
The edition attribute is deprecated:
warning: flake 'git+file:///home/vin/workspace/vcs/naersk' has deprecated attribute 'edition'
> flake: remove edition and format

- test.nix
> add musl test

- .github/actions/nix/install-nix
This pulls @knl's fix from https://github.com/nmattia/niv/pull/305
> FIx GitHub action

- lib.nix
We were using the first encountered dependency _by name_ from the
lockfile, although the revision may not have been correct.
> Fix picking wrong git dep

- build.nix
- config.nix
Fixes https://github.com/nmattia/naersk/issues/102
> add cargoDocOptions and cargoDocCommands

- lib.nix
- nix/sources.json
- test.nix
> Make sure patched dependencies are left intact

- build.nix
- config.nix
> Don't rely on unstable flags

- build.nix
Hi there,
I wasn't able to reproduce a hello world crate when built multiple times:
```
❯ nix build . -L --enforce-determinism --repeat 2 --keep-failed
warning: Git tree '/home/opeik/dev/hello-world' is dirty
hello-world-deps> unpacking sources
hello-world-deps> unpacking source archive /nix/store/kcijkqzh45qv5hr6jjg7s5qn3jbhdj7f-dummy-src
hello-world-deps> source root is dummy-src
hello-world-deps> patching sources
hello-world-deps> configuring
hello-world-deps> [naersk] cargo_version (read): 1.56.0 (4ed5d137b 2021-10-04)
hello-world-deps> [naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
hello-world-deps> [naersk] cargo_release: --release
hello-world-deps> [naersk] cargo_options: --locked
hello-world-deps> [naersk] cargo_build_options: $cargo_release -j …
```
> Fix non-deterministic dependency builds

- README.md
- README.tpl.md
Looks like I've stumbled upon https://github.com/isaacs/github/issues/1681, making me unable to push changes to pull requests; I'm not sure on the GitHub terminology, but maybe-just-maybe getting my first change merged here will do.
> readme: Remove invalid link for `Comparison`

- lib.nix
Makes `cargo fmt --check` happy
> Make dummy-src respect cargo fmt

- examples/multi-target/flake.nix
Just copying x86_64 example and changing it to i686 doesn't work, so I've figured out a hacky way of doing it and wanted to document it somewhere visible.
> examples: Add i686-pc-windows-gnu to multi-target

- README.md
- README.tpl.md
Closes https://github.com/nix-community/naersk/issues/283.
> Improve README

- README.md
- README.tpl.md
> readme: Add an example of examples

- config.nix
(patch from an email, thanks to jos@nlnet.nl)
> Look in [workspace.package] for the version number

- README.md
- README.tpl.md
I don't have much time nowadays to manage Naersk, so it's time to give the scepter :-)
> readme: Add maintainer status

- default.nix
Search for `.cargo/config.toml` as well as `.cargo/config`.
> Support .cargo/config.toml
